site_name: Sitemap Grabber
site_description: Grab and recursively parse website sitemaps, robots.txt, and other related files.
repo_url: https://github.com/simplecto/sitemap_grabber
repo_name: simplecto/sitemap_grabber

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - API Reference: api.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
