[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sitemap_grabber"
authors = [{name = "SimpleCTO", email = "github+sitemap_grabber@simplecto.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
  "requests",
  "fake-useragent",
  "defusedxml"
]

[project.urls]
Home = "https://simplecto.com"
